### ISSUE TITLE
Upgrade to new compiler v0.11

### ISSUE THREAD

**Issue by klangner** [nwolverson/purescript-csv#10]
It looks that the new Purescript compiler is out and on the pursuit all packages related to the old compiler are hidden. This is (I guess) because they are not compatible with the new compiler.
So to be able to use this library with current projects it is necessary to upgrade it to new compile too.

Could you publish new version? It requires updating purescript and all packages in bower.json.

If you luck time to do it, let me know. I can prepare PR with the changes

**Comment by nwolverson** [comment]
Should get to this today. Please do follow up if I don't!

**Comment by nwolverson** [comment]
Released
