### ISSUE TITLE
I have registered a package under

### ISSUE THREAD

**Issue by robkuz** [nwolverson/purescript-csv#3]
Hi,

I update the package for run on 0.8 and have registered it with bower under purescript-csv-rk so you can register yours under purescript-csv still.

Would you be so kind to accept the pull request (if its up to your liking of course) and the register your package?

best regards

Robert

**Comment by nwolverson** [comment]
As per the PR comments, sorry for the delay.

I've registered purescript-csv on bower. Happy to add you as collaborator if that would be useful, but I should be more responsive now.

**Comment by nwolverson** [comment]
Closing this as PR has been accepted and package registered as suggested.
